### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by consultantRR** [kenjij/lita-slack#42]
Seeing lita-slack crash frequently, as follows:

```
/usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/lita-slack-1.5.0/lib/lita/adapters/slack/message_handler.rb:102:in `gsub': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/lita-slack-1.5.0/lib/lita/adapters/slack/message_handler.rb:102:in `remove_formatting'
	from /usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/lita-slack-1.5.0/lib/lita/adapters/slack/message_handler.rb:43:in `body'
	from /usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/lita-slack-1.5.0/lib/lita/adapters/slack/message_handler.rb:115:in `dispatch_message'
	from /usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/lita-slack-1.5.0/lib/lita/adapters/slack/message_handler.rb:158:in `handle_message'
	from /usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/lita-slack-1.5.0/lib/lita/adapters/slack/message_handler.rb:17:in `handle'
	from /usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/lita-slack-1.5.0/lib/lita/adapters/slack/rtm_connection.rb:99:in `block in receive_message'
	from /usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/lita-slack-1.5.0/lib/lita/adapters/slack/event_loop.rb:9:in `block in defer'
	from /usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `call'
	from /usr/local/rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `block in spawn_threadpool'
```

**Comment by freibuis** [comment]
interesting. this might be OS related.  you wouldn't happen to be running this on windows by any chance?

**Comment by jimmycuadra** [comment]
It might be this: jimmycuadra/lita-hipchat#3

**Comment by consultantRR** [comment]
No, running in Centos 6.6 within a Docker container. Let me know if any testing would be useful. Happy to help.

**Comment by consultantRR** [comment]
Okay, I have added this to the Dockerfile in my Centos environment:

```
RUN localedef -c -f UTF-8 -i en_US en_US.UTF-8
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  
```

The container now reports this:

```
# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

I will keep an eye on this to see if this issue recurs, and will report back.

**Comment by consultantRR** [comment]
Just reporting back that, after the above post, this seems to have stabilized.
